USE MASTER
GO
CREATE DATABASE QLDA_PS24083_TRUONG
ON 
(		NAME  = QLDA_PS24083_TRUONG_dat,
		FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\QLDA_PS24083_TRUONG.mdf',
		SIZE = 10,
		MAXSIZE = 50,
		FILEGROWTH = 5
)
LOG ON 
(		
		NAME  = QLDA_PS24083_TRUONG_log,
		FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\QLDA_PS24083_TRUONG.ldf',
		SIZE = 10MB,
		MAXSIZE = 50MB,
		FILEGROWTH = 5MB		
)
GO 
USE QLDA_PS24083_TRUONG
GO

CREATE TABLE PHONGBAN 
(
	TENPHG NVARCHAR(15),
	MAPHG INT  NOT NULL PRIMARY KEY,
	TRPHG NVARCHAR(9) NOT NULL  ,
	NG_NHANCHUC DATE NOT NULL 
)
CREATE TABLE NHANVIEN 
(
	HONV NVARCHAR(15) NOT NULL,
	TENLOT NVARCHAR(15) NOT NULL,
	TENNV NVARCHAR(15) NOT NULL,
	MANV NVARCHAR(9) NOT NULL PRIMARY KEY ,
	NGSINH DATE NOT NULL,
	DCHI NVARCHAR(30) NOT NULL,
	PHAI NVARCHAR(15) NOT NULL,
	LUONG FLOAT NOT NULL,
	MA_NQL NVARCHAR(9) REFERENCES NHANVIEN(MANV) ,
	PHG INT  NOT NULL 
)

CREATE TABLE DIADIEM
(
	MAPHG  INT REFERENCES PHONGBAN(MAPHG) NOT NULL,
	DIADIEM NVARCHAR(45) ,
	PRIMARY KEY (MAPHG,DIADIEM)
)
CREATE TABLE THANNHAN
(
	MA_NVIEN NVARCHAR(9) NOT NULL REFERENCES NHANVIEN(MANV) ,
	TENTN NVARCHAR(15) NOT NULL ,
	PHAI NVARCHAR(15) NOT NULL,
	NGSINH DATE NOT NULL,
	QUANHE NVARCHAR(15) NOT NULL,
	PRIMARY KEY(MA_NVIEN,TENTN)

)
CREATE TABLE DEAN
(
	TENDA NVARCHAR(15) NOT NULL,
	MADA INT NOT NULL PRIMARY KEY,
	DDIEM_DA NVARCHAR(45) NOT NULL,
	PHONG INT  NOT NULL REFERENCES PHONGBAN(MAPHG)
)
CREATE TABLE CONGVIEC
(
	MADA INT NOT NULL REFERENCES DEAN(MADA) ,
	STT INT  NOT NULL ,
	TEN_CONG_VIEC NVARCHAR(50) NOT NULL,
	PRIMARY KEY(MADA,STT)
	
)
CREATE TABLE PHANCONG
(
	MA_NVIEN NVARCHAR(9) REFERENCES NHANVIEN(MANV) NOT NULL ,
	MADA INT NOT NULL  ,
	STT INT  NOT NULL ,
	THOIGIAN FLOAT ,
	FOREIGN KEY (MADA,STT) REFERENCES CONGVIEC(MADA,STT),
	PRIMARY KEY(MA_NVIEN,MADA,STT)
)

-- ADD FOREIGN KEY OF NHANVIEN AND PHONGBAN JOIN WITH
ALTER TABLE NHANVIEN ADD CONSTRAINT FK_INPHONGBAN FOREIGN KEY (PHG) REFERENCES PHONGBAN(MAPHG)
ALTER TABLE PHONGBAN ADD CONSTRAINT FK_INNHANVIEN FOREIGN KEY (TRPHG) REFERENCES NHANVIEN(MANV)











