-- VIET SP THEM 1 PHONG BAN . CAC THONG TIN DUOC TRUYEN VAO QUA THAM SO (CO KIEM TRA LOI)

USE QLDA_PS24083_TRUONG
GO 
CREATE PROCEDURE ADD_PHG @MA INT , @TEN NVARCHAR(15) , @TRP NVARCHAR(9) ,@NGAY date
AS 

		BEGIN 
		BEGIN TRY
			INSERT INTO PHONGBAN VALUES 
				 (@TEN,@MA,@TRP,@NGAY)		 
			PRINT 'THEM THANH CONG'
		END TRY
		BEGIN CATCH
		PRINT CASE  ERROR_NUMBER()
			WHEN 2627 THEN 'TRUNG MA PHONG'
			WHEN 547 THEN 'MA TRUONG PHONG KHONG CO '
			WHEN 515 THEN 'CHUA NHAP DU THONG TIN'
			ELSE 'LOI' + ERROR_MESSAGE()
			END
		END CATCH
		END

		EXECUTE ADD_PHG  1562,N'KINH DOANH',N'03','2022-05-28'
SELECT * FROM PHONGBAN

select format(45435345345,'#,##0.00') + 'vnd'
SELECT FORMAT(8000, '#,###.000')
select format(getDate(),'dd//MM/yyyy')

USE QLDA_PS24083_TRUONG
GO 
CREATE PROCEDURE usp_AddPhongBan 
		@MAPHG SMALLINT,@TENPHG NVARCHAR(15),@TRPHG NVARCHAR(9),@NG_NHANCHUC DATETIME = NULL
AS
BEGIN
	BEGIN TRY
		INSERT INTO PHONGBAN(MAPHG,TENPHG,TRPHG,NG_NHANCHUC) VALUES
			(@MAPHG,@TENPHG,@TRPHG,@NG_NHANCHUC)
			PRINT N'Thêm thành công!';
	END TRY
	BEGIN CATCH
		print N'thêm thất bại!'
		print	case error_number()
					when 2627 then N'Trùng khóa chính'
					when 547 then N'Mã phòng trùng'
					when 515 then N'Rỗng'
					else 'Lỗi '+ error_message()
				end
	END CATCH
END

execute usp_AddPhongBan 1,N'Điều hành','001','12-12-2003'
