USE QLDA_PS24083_TRUONG
BEGIN TRY
INSERT INTO PHONGBAN VALUES 
(101,'d','001','01/01/2022')
END TRY
BEGIN CATCH 
DECLARE @MSG VARCHAR(100)
 SET @MSG = CASE ERROR_NUMBER()
 WHEN 2627 THEN 'TRUNG KHOA CHINH' -- KHOA CHINH TRUNG , 
 WHEN 547 THEN 'MA TRUONG PHONG KHONG CO' -- MA KHONG TON TAI KHOA CHINH , MA KHOA NGOAI NHAP
 WHEN 515 THEN 'DU LIEU CHUA NHAP DU' -- NULL
 when 245 then 'tu char k sang int dc'
 ELSE 'LOI '+  CAST(ERROR_NUMBER() AS CHAR) 
 END
 print @MSG
 RAISERROR(@MSG,15,1) -- 1 trang thai loi,level 15
END CATCH
select * from PHONGBAN

